name: "Build and Deploy to GH Pages"
on: 
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: CardGame
  PROJECT_PATH: project

jobs:
  export-web:
    name: Web Export
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build/web
      - name: GitHub Pages Deployment
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: build/web
          ssh-key: ${{ secrets.DEPLOY_KEY }} 
      # - name: Install rsync and ssh
      #   run: |
      #     apt-get update && apt-get install -y rsync ssh
      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@releases/v4
      #   with:
      #     branch: gh-pages
      #     folder: build/web
      #     ssh-key: ${{ secrets.DEPLOY_KEY }}           